# Generated by Django 5.1.4 on 2025-12-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipment_serial_number_equipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='reject_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
