# Generated by Django 5.1.4 on 2025-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_requisition_approve_date_requisition_reject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
